language: node_js
node_js:
  - stable
sudo: false
cache:
  npm: true
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm test
after_success:
  - echo "All good! 🎉"